task: Wav2LipHD_patchGAN

base_config: SyncNetHD/base_config.yaml

data:
  data_root: /data/julianlu/Experiment/Wav2LipHD/preprocessed_data/mix_ZYDH6PAD50_LRS3SPK90
  train_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk_BLSilence/train_unbal.txt
  val_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk_BLSilence/val.txt

  pre_calculate_mels: true
  pre_calculate_dir: cache_wav2lipCN_patchGAN_Aug
  pre_calculate_threads: 16

  audio_augment: false
  img_augment: true
  gaussian_noise_prob: 0.1
  freq_mask_prob: 0.1
  pitch_shift_prob: 0.1

model:
  use_SyncNetHD: false
  permute_disc_data: false
  disc_weight: 0
  sync_weight: 0.01
  patchgan_weight: 0.01
  syncnet_ckpt: /data/julianlu/Experiment/Wav2LipHD/checkpoints/lipsync_expert.pth
  disc_ckpt: ""
  wav2lip_ckpt: exp/Wav2LipHD_patchGAN_CN/LRS520En_BC12_LR1e-4_MAV4_run1_DFSync_dwt0_swt0.01_pwt0.01/checkpoint_step242000.pth

runtime:
  nepochs: 10000000
  steps_per_epoch: 50
  batch_size: 16  # 8 with 1 GPU, 16 with 2 
  model_learning_rate: 0.0001
  disc_learning_rate: 0.0001
  patchgan_learning_rate: 0.0001
  num_workers: 8
  checkpoint_interval: 2000
  eval_interval: 500
  eval_forward_steps: 10
  save_optimizer_state: true
  checkpoint_dir: exp/Wav2LipHD_patchGAN_CN/LRS520En_BC12_LR1e-4_MAV4_run2_DFSync_dwt0_swt0.01_pwt0.01_ImgAug

wandb:
  name: run1_DFSync_patchGAN_dwt0.01_swt0.01_pwt0.01_imgAug
  enable: true
  project: Wav2LipHD
  tags: ["MARV4.0", "ImgAug", "run2"]
  notes: null
  group: 'patchGAN_CN'
  resume: false