task: Wav2LipHD

base_config: SyncNetHD/base_config.yaml

data:
  data_root: /data/julianlu/Experiment/Wav2LipHD/preprocessed_data/mix_ZYDH6PAD50_LRS3SPK90
  train_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk_BLSilence/train_unbal.txt
  val_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk_BLSilence/val.txt

  pre_calculate_mels: true
  pre_calculate_dir: cache_wav2lipCN
  pre_calculate_threads: 16

  audio_augment: false
  gaussian_noise_prob: 0.1
  freq_mask_prob: 0.1
  pitch_shift_prob: 0.1

model:
  use_SyncNetHD: false
  permute_disc_data: true
  disc_weight: 0.01
  sync_weight: 0.01
  syncnet_ckpt: /data/julianlu/Experiment/Wav2LipHD/checkpoints/lipsync_expert.pth
  disc_ckpt: exp/Wav2LipHD_CN/LRS520En_BC12_LR1e-4_MAV4_run3_AugPerm_DFSync_dwt0.01_swt0.01/disc_checkpoint_step318000.pth
  wav2lip_ckpt: exp/Wav2LipHD_CN/LRS520En_BC12_LR1e-4_MAV4_run3_AugPerm_DFSync_dwt0.01_swt0.01/checkpoint_step318000.pth

runtime:
  nepochs: 10000000
  steps_per_epoch: 50
  batch_size: 10  # 8 with 1 GPU, 16 with 2 
  model_learning_rate: 0.0001
  disc_learning_rate: 0.0001
  num_workers: 8
  checkpoint_interval: 2000
  eval_interval: 500
  eval_forward_steps: 10
  save_optimizer_state: true
  checkpoint_dir: exp/Wav2LipHD_CN/LRS520En_BC12_LR1e-4_MAV4_run3_AugPerm_DFSync_dwt0.01_swt0.01

wandb:
  name: run3_DFSync_AugPerm_dwt0.01_swt0.01_continue3
  enable: true
  project: Wav2LipHD
  tags: ["MARV4.0", "NoAug", "run1"]
  notes: null
  group: 'ZYDFLRS90_CN'
  resume: false