task: LdmkSync

base_config: LdmkSync/base_config.yaml

data:
  data_root: /data/julianlu/Experiment/Wav2LipHD/preprocessed_data/mix_ZYDH6PAD50_LRS3SPK90
  train_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk/train_old.txt
  val_list: /data/julianlu/Experiment/Wav2LipHD/filelists/ZYDH6_LRS_90spk/val.txt
  
  pre_calculate_mels: true
  pre_calculate_dir: cache_LdmkSync_aug
  pre_calculate_threads: 12

  random_displace_prob: 0.05
  random_displace_scale: 0.0001
  random_rotate_prob: 0.05
  random_rotate_degree: 30
  random_rotate_displace: [0, 0]

model:
  resume_ckpt: ""
  resume_ckpt_config: false

runtime:
  nepochs: 10000000
  steps_per_epoch: 10
  batch_size: 256
  init_learning_rate: 0.001
  num_workers: 8
  checkpoint_interval: 1000
  eval_interval: 100
  eval_forward_steps: 10
  save_optimizer_state: true
  checkpoint_dir: exp/LdmkSync/ZYDH6LRS90_BC256_LR1e-3_MAV4.0_LdmkAug


wandb:
  name: ZYDH6LRS90_MAV4.0_LdmkAug
  enable: true
  project: LdmkSync
  tags: ["MAV4.0", "LdmkAug"]
  notes: ""
  group: "LdmkAug_Mel"
  resume: false
  