task: SyncNet

base_config: SyncNet/base_config.yaml

data:
  data_root: preprocessed_data/LRS3_TED_1500
  train_list: filelists/LRS3_TED_15000/train.txt
  val_list: filelists/LRS3_TED_15000/val.txt
    
  pre_calculate_mfcc: true
  pre_calculate_dir: cache_syncnetDF
  pre_calculate_threads: 16


model:
  resume_ckpt: exp/SyncNetDF/SyncNetDF_TED1500_bc384_lr0.001/checkpoint_step42000.pth
  resume_ckpt_config: false

runtime:
  nepochs: 10000000
  steps_per_epoch: 10
  batch_size: 384
  init_learning_rate: 0.001
  num_workers: 8
  checkpoint_interval: 1000
  eval_interval: 100
  eval_forward_steps: 10
  save_optimizer_state: true
  checkpoint_dir: exp/SyncNetDF/SyncNetDF_TED1500_bc384_lr0.001

wandb:
  name: MFCC_run1_continue
  enable: true
  project: LRS1500
  tags: ["MFCC", "NoAug"]
  notes: ""
  group: 'LRS1500'
  resume: false
  