task: SyncNetHD

base_config: SyncNetHD/base_config.yaml

data:
  data_root: preprocessed_data/LRS3_TED_1500
  train_list: filelists/LRS3_TED_15000/train.txt
  val_list: filelists/LRS3_TED_15000/val.txt
  
  pre_calculate_mels: true
  pre_calculate_dir: cache_syncnetColor
  pre_calculate_threads: 32


model:
  use_SyncNetHD: false 
  resume_ckpt: checkpoints/lipsync_expert.pth
  resume_ckpt_config: false

runtime:
  nepochs: 10000000
  steps_per_epoch: 10
  batch_size: 256
  init_learning_rate: 0.001
  num_workers: 16
  checkpoint_interval: 2000
  eval_interval: 100
  eval_forward_steps: 10
  save_optimizer_state: true
  checkpoint_dir: exp/SyncNetColor/LRS1500En_BC256_LR1e-3_MAV4_NoAug


wandb:
  name: SyncNetColor
  enable: true
  project: LRS1500
  tags: ["MAV4.0", "NoAug"]
  notes: "w/o rescale cosine similarity, keep consistant with raw implementation of Wav2Lip"
  group: 'SyncNetColor'
  resume: false
  